config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :hearts, only: :create
  get "about" => 'pages#about'
  root 'pages#welcome'

  

end

app/models/heart.rb
class Heart < ActiveRecord::Base
	belongs_to :post 
	validates :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :hearts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
	def create
		@heart = Heart.new(heart_params)

    
      if @heart.save
        redirect_to @heart.post, notice: 'Hearted that post!' 
        
      else
         redirect_to root_url, notice: "Had an issue creating that heart."
        
      end
	end

	private
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:heart).permit(:post_id)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def welcome
  	@posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  
  def index
    @posts = Post.all
  end

  # GET /posts/1
  
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  
  def create
    @post = Post.new(post_params)

    
      if @post.save
        redirect_to @post, notice: 'Post was successfully created.' 
        
      else
         render :new 
        
      end
    
  end

  # PATCH/PUT /posts/1
  
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.' 
    else
        render :edit 
        
      
    end
  end

  # DELETE /posts/1
  
  def destroy
    @post.destroy
    
      redirect_to posts_url, notice: 'Post was successfully destroyed.' 
     
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :kind, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>
	<head>
	  <title>Crumblr</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>

	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

	</head>
	<body>
		<div class="container">
			<div class="page-header">
				<h1>
					<%= link_to 'crumblr', '/'%>
					<small>// home baked goodness</small>
				</h1>
			</div>


			<ul class="nav nav-pills pull-right">
				<li>
		<%= link_to "Home", root_url %>
	</li>
	<li>
		<%= link_to "Manage Posts", posts_url %>
	</li>
	<li>
		<%= link_to "About", about_url %>
	</li>
			</ul>

			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					

				</div>
			</div>


	<%= yield %>
</div>

	</body>
	</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/welcome.html.erb
<% @posts.each do |post| %>
<%= render 'posts/post', post: post %>
	<br/> <br/> <br/> <br/>
	<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label  :kind %><br>
    <%= f.select :kind, ["text", "image"], {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p>
  
  <h2>
  	<%= link_to post.title, post %>
  	<div class="pull-right">
  		<%= form_for(Heart.new) do |f| %>
  		<%= f.hidden_field :post_id, value: post.id %>
  		<%= f.submit "♥", class: 'btn btn-danger' %>
  		<% end %>
  	</div>
  </h2>
</p>

<p>
  <% if post.kind == 'image' %>
  <%= image_tag post.content, style: "width: 100%" %>
  <% else %>
  <%= simple_format post.content %>
  <% end %>
</p>

<p class="text-muted">
	<small>
	Posted on <%=post.created_at.to_formatted_s(:long)%>
</small>
<small class="pull-right"> 
	<%= post.hearts.count %> hearts
</small>
</p>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.content, length: 100) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if notice.present? %>
<p class="alert alert-info"> 
	<%= notice %>
</p>
	<%end%>

<%= render 'post', post: @post %>